package software.leonov.concurrent;

import static java.util.Objects.requireNonNull;

import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.RejectedExecutionException;
import java.util.concurrent.Semaphore;

/**
 * A {@code BoundedExecutor} enforces a limit on the maximum number of tasks that can be
 * {@link Executor#execute(Runnable) executed} concurrently by another {@code Executor}. Once the maximum number of
 * tasks are executing attempts to execute another task will block until a previous task completes.
 * <p>
 * Users can use this class to control the concurrency in different sections of their code to avoid overloading a shared
 * global thread pool.
 * <p>
 * <b>Note:</b> This class is not designed to directly restrict the number of threads generated by the underlying
 * executor. The bounding mechanism focuses solely on limiting the number of tasks accepted for execution.
 * <p>
 * The precise definition of {@link Executor#execute(Runnable) execute} is solely defined by the underlying executor,
 * and may include putting pending tasks on a queue when the executor is busy, for example when using a standard
 * {@link Executors#newFixedThreadPool(int) fixed thread pool}. In any case, <b><u>in order for the bounding mechanism
 * to function correctly the underlying executor MUST be able to accept an unlimited number of tasks for
 * execution.</b></u> See {@link BoundedExecutorService} for further discussion.
 *
 * @author Zhenya Leonov
 */
public final class BoundedExecutor implements Executor {

    private final Executor  exec;
    private final Semaphore semaphore;
    private final int       ntasks;

    /**
     * Creates a new {@code BoundedExecutor} which will limit the maximum number of tasks that can be executed concurrently
     * by the underlying {@code Executor}.
     * 
     * @param exec   the underlying executor
     * @param ntasks the maximum number of tasks allowed to execute concurrently
     */
    public BoundedExecutor(final Executor exec, final int ntasks) {
        requireNonNull(exec, "exec == null");

        if (ntasks < 1)
            throw new IllegalArgumentException("ntasks < 1");

        this.exec      = exec;
        this.semaphore = new Semaphore(ntasks);
        this.ntasks    = ntasks;
    }

    /**
     * {@inheritDoc}
     * <p>
     * If this thread is interrupted while waiting to execute the command this method will return immediately and this
     * thread's {@link Thread#isInterrupted() interrupted} status will be set to {@code true}.
     */
    @Override
    public final void execute(final Runnable command) {
        requireNonNull(command, "command == null");

        try {
            semaphore.acquire();
            exec.execute(() -> {
                try {
                    command.run();
                } finally {
                    semaphore.release();
                }
            });
        } catch (final RejectedExecutionException e) {
            semaphore.release();
            throw e;
        } catch (final InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    /**
     * Returns the underlying {@code Executor}.
     * 
     * @return the underlying {@code Executor}
     */
    public Executor getDelegate() {
        return exec;
    }

    @Override
    public String toString() {
        return this.getClass().getSimpleName() + "[" + exec.toString() + ", bound = " + ntasks + "]";
    }

}